application: sem-loxal
version: a
runtime: go
api_version: 1

handlers:
# should precede ".*" (main URL handler)
- url: /static
  static_dir: static
# should precede ".*" (main URL handler)
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
#- url: /post
#  script: _go_app
#  login: required
- url: /.*
  script: _go_app
