application: sem-loxal
version: a
runtime: go
api_version: 1

handlers:
#- url: /post
#  script: _go_app
#  login: required
#
#- url: /store
#  script: _go_app
#  login: required

- url: /.*
  script: _go_app
  login: required
