application: sem-loxal
version: c
runtime: go
api_version: 1

handlers:
# should precede ".*" (main URL handler)
- url: /static
  static_dir: static
# should precede ".*" (main URL handler)
- url: /favicon.ico
  static_files: static/theme/favicon.ico
  upload: static/theme/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /client/(.*)
  static_files: static/client/\1
  upload: static/client/.*
- url: /resource/(.*)
  static_files: static/resource/\1
  upload: static/resource/.*
#- url: /start
#  static_files: static/client/site/main.html
#  upload: /static/client/site/main.html
- url: .*
  script: _go_app
#  login: required
